### ISSUE TITLE
The project is unable to function properly.

### ISSUE THREAD

**Issue by Cullwen** [nghlt/Downgrade-MAS-Applications#1]
In step 4 "Capture a list of App Version IDs", it cannot find the domain "https://p-buy.itunes.apple.com/WebObjects/MZBuy.woa/wa/buyProduct?guid=" from the appstoreagent process in Proxyman. It can only find "https://p*-buy.itunes.apple.com" without any relevant information about the request body. Is this due to an issue with the Proxyman version or the macOS system version?

**Comment by nghlt** [comment]
`p*-buy.itunes.apple.com` is the proper destination, such as `p7-buy.itunes.apple.com`. Please take a look into response body instead of request body.

**Comment by Cullwen** [comment]
I can only find "https://p-buy.itunes.apple.com", but I cannot find the character mentioned in the README "~ /WebObjects/MZBuy.woa/wa/buyProduct?guid=". Additionally, when I checked the body under the response, it was empty. Perhaps this is because I was performing an update instead of a download in the macOS App Store?

**Comment by nghlt** [comment]
I can't reproduce that issue on my Mac. You can try downloading another app and then check the requests. If you can confirm that the issue is related to updating rather than downloading the app, the only solution is to uninstall it and start again.

**Comment by Cullwen** [comment]
OK, can you provide the version of Proxyman you are currently using? I try again. Thank you.

**Comment by nghlt** [comment]
I'm using the lasted version, `v4.14.0`, on MacOS `13.6.1`

**Comment by Cullwen** [comment]
From the results, I can exclude the reasons for updating or downloading. Can you help me figure out where the problem is? After executing the command in the terminal, an error occurred. Additionally, is Proxyman unable to start HTTP properly? But I checked the official documentation and ruled out issues with installing and trusting certificates, or it could be a network problem?
<img width="697" alt="截屏2023-12-03 17 24 42" src="https://github.com/nghlt/Downgrade-MAS-Applications/assets/99164208/8b702c5b-33ae-4f96-b455-372c26754093">
<img width="1160" alt="截屏2023-12-03 17 30 03" src="https://github.com/nghlt/Downgrade-MAS-Applications/assets/99164208/014882c6-959a-4860-abca-64e2115efc41">
<img width="812" alt="截屏2023-12-03 17 27 20" src="https://github.com/nghlt/Downgrade-MAS-Applications/assets/99164208/15446a77-4e0e-46f9-aaae-452a8ae4b5af">

**Comment by nghlt** [comment]
I see. Your Mac is under SIP protected mode (SIP status is on). Therefore the frida-tools can not work properly. Please follow the instruction in [Requirements](https://github.com/nghlt/Downgrade-MAS-Applications#requirements)

**Comment by Cullwen** [comment]
I ensured to execute "csrutil disable" in Terminal under Recovery Mode to disable SIP. At the moment, I can only try again. If it doesn't work, I'll have to give up. I just want to extract the pkg file for Notability 12.1.8. I will be immensely grateful if you can assist me with that (Ref: https://www.freesion.com/article/10301469940/). Regardless, thank you for your previous response and help. This is indeed an excellent project and currently the only method available to downgrade app versions on the MacOS App Store.

**Comment by nghlt** [comment]
The error message indicated this issue related to Mac M1. Try running this command:

`sudo nvram boot-args="-arm64e_preview_abi"`

And then rebooting
c: [Mac M1: Frida-Trace: '(os/kern) protection failure'](https://github.com/frida/frida/issues/1717#issuecomment-959044802)

**Comment by Cullwen** [comment]
After executing the code on the link you provided, it is working fine. Thank you for your help！

**Comment by codezi** [comment]
Hello @nghlt ,
When I run 
frida appstoreagent -l ~/Downloads/disable_ssl_pinning.js
It shows this error. Can you help me? Thank you.
```

frida appstoreagent -l ~/Downloads/disable_ssl_pinning.js
     ____
    / _  |   Frida 17.4.0 - A world-class dynamic instrumentation toolkit
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at https://frida.re/docs/home/
   . . . .
   . . . .   Connected to Local System (id=local)
                                                                                
TypeError: not a function
    at <eval> (/Users/name/Downloads/disable_ssl_pinning.js:9)

```

I am using mac with M4 chip.

**Comment by nghlt** [comment]
@codezi what MacOS version are you running on?

**Comment by codezi** [comment]
> [@codezi](https://github.com/codezi) what MacOS version are you running on?

I created new issue in here: https://github.com/nghlt/Downgrade-MAS-Applications/issues/3

Thank you.
