### ISSUE TITLE
Unable to find 'softwareVersionExternalIdentifiers' key

### ISSUE THREAD

**Issue by lumen-novum** [nghlt/Downgrade-MAS-Applications#2]
In step 4, I can't find the 'softwareVersionExternalIdentifiers' key. The response does exist, but I wasn't able to find that or the 'appExtVrsId' key (the body instead contains unrelated keys).

What should I do?

MacOS 14.6.1

**Comment by nghlt** [comment]
> The response does exist


The MITM attack failed, preventing you from inspecting the request. This could be due to SSL pinning not being disabled or an untrusted root certificate.
